### PR TITLE
Make haskell-opentracing work with recent Jaeger

### PR DESCRIPTION
**Pull request by abailly**
This is a preliminary PR that's unfortunately rather large. It makes it possible to work with a recent Jaeger server:
* Use stack
* Updates to thrift 0.11 (this unfortunately involves vendoring thrift repository in `stack.yaml` to some specific version)
* Drop use of backpack signatures (stack does not support backpack)
* Make WAI middleware use `uber-trace-id` and propagate that in current context
* Make `Tracer` threadsafe (stores `TracingContext` indexed by `ThreadId`)

Feedback welcomed!

### CODE REVIEW

**Comment by abailly** [comment]
I think this also addresses #3

**Comment by ocharles** [comment]
Thank you, but I'm not pursuing this project anymore. Perhaps it would be best if you forked the repository and carried on work? Alternatively, I can give you commit rights here.

**Comment by abailly** [comment]
that's why I kind of inferred from the lack of activity :) Are you not using opentracing anymore or is this project superseded by something else?

**Comment by abailly** [comment]
@ocharles But I am fine with forking and taking it over unless you point me to some alternative solution.

**Comment by ocharles** [comment]
More that I never got beyond a hobby/experiment stage. This never made it to production.

> I am fine with forking and taking it over

I think that's the best path here.

**Comment by ocharles** [comment]
Oh, and of course - good luck! I'll watch your repository :smile:

**Comment by abailly** [comment]
Thanks! Actually, it works quite well but it took me some time to fix various issues here and there.

**Comment by abailly** [comment]
And of course, thanks for starting this up ;-)

**Comment by abailly** [comment]
And it's a pity stack does not yet support backpack modules...

**Pull request closed without merging**
